logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    com.sunglowsys: DEBUG
server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atithih_db
    username: root
    password: root
  jpa:
      hibernate:
          ddl-auto: update
          dialect: org.hibernate.MYSQL8Dialect
